version: '3'
services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: rails
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "3310:3306"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/pictweet
    ports:
      - "3000:3000"
    depends_on:
      - db

